# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d04285ecc9f1da3434dfe3be940c481c49eebd1d4eb2655a819a3698f74808cf5cbfe4fa271fa6431c2406f8cff90f50205a09b81c0905f3c3149165aebab48

test:
  secret_key_base: 4b97173a121c335aa620f6d9cfe25803132872554485745214f4ca56a0ef9a68dfe541bf02ddb1d1f1be0d07a7bd967542d67ff5148b25622425516cbd4315e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
